### ISSUE TITLE
NameError: name 'processors' is not defined

### ISSUE THREAD

**Issue by arzWZM** [phsmith/python#2]
Hi, I'm getting a NameError. This happens only with Windows Vmware snmp data. Linux Vmware snmp data doesn't produce this error.

Traceback (most recent call last):
  File "fusioninventory-xmlgenerator2", line 319, in <module>
    SubElement(hardware, 'PROCESSORS').text = processors
NameError: name 'processors' is not defined

**Comment by phsmith** [comment]
@arzWZM Could you attach a example of that snmp data?

**Comment by arzWZM** [comment]
Attached.

[test.snmp.txt](https://github.com/phsmith/python/files/5135789/test.snmp.txt)

**Comment by arzWZM** [comment]
Attached.

[test.snmp.txt](https://github.com/phsmith/python/files/5135815/test.snmp.txt)

**Comment by phsmith** [comment]
@arzWZM I've just pushed a fix, You can try that again.

**Comment by arzWZM** [comment]
That fixed the issue. There is another small issue related to processor count. I'll report that in a minute
